console:
    excluded:
        - 'assets:install'
        - 'cache:clear'
        - 'cache:pool:clear'
        - 'cache:pool:delete'
        - 'cache:pool:list'
        - 'cache:pool:prune'
        - 'cache:warmup'
        - 'config:dump-reference'
        - 'debug:autowiring'
        - 'debug:config'
        - 'debug:container'
        - 'debug:event-dispatcher'
        - 'debug:router'
        - 'lint:container'
        - 'lint:yaml'
        - 'router:match'
        - 'secrets:decrypt-to-local'
        - 'secrets:encrypt-from-local'
        - 'secrets:generate-keys'
        - 'secrets:list'
        - 'secrets:remove'
        - 'secrets:set'
