version: '3'

services:
    phpbenchmarks_benchmark_kit:
        container_name: phpbenchmarks_benchmark_kit
        tty: true
        build:
            context: ../
            dockerfile: docker/Dockerfile
            args:
                DOCKER_UID: ${DOCKER_UID}
        environment:
            - NGINX_PORT=${NGINX_PORT}
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ${INSTALLATION_PATH}:/var/www/phpbenchmarks
            - ../src:/var/phpbenchmarks
        extra_hosts:
            - php56.benchmark.loc:127.0.0.1
            - php70.benchmark.loc:127.0.0.1
            - php71.benchmark.loc:127.0.0.1
            - php72.benchmark.loc:127.0.0.1
            - php73.benchmark.loc:127.0.0.1
