services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $opcachePreloadUser: '%env(OPCACHE_PRELOAD_USER)%'

    Huttopia\ConsoleBundle\Command\ListCommand:
        class: App\Command\DefaultCommand

    App\Command\:
        resource: '../src/Command/**/*Command.php'
