services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $opcachePreloadUser: '%env(OPCACHE_PRELOAD_USER)%'

    App\Command\:
        resource: '../src/Command/**/*Command.php'
